import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter, Roboto } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], weight:["400", "700"] });
const roboto =  Roboto({ subsets: ['latin'], weight:["400"] });





export const metadata: Metadata = {
  title: "Dgdsr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <div className={inter.className}></div>
        {children}
      </body>
    </html>
  );
}
